"use client";

import { useEffect, useState } from 'react';
import { api } from '@/lib/api/client';
import { formatDate } from '@/lib/utils';
import { ScrollText, Wand2, Clock, ChevronRight, AlertCircle, FileText } from 'lucide-react';
import Link from 'next/link';

export default function Battlecards() {
    const [competitors, setCompetitors] = useState([]);
    const [loading, setLoading] = useState(true);

    async function fetchBattlecardStatus() {
        try {
            const res = await api.getCompetitors();
            const comps = res.data;

            // For each competitor, we could try to get their battlecard status
            // But let's just show them all and the "View/Generate" options
            setCompetitors(comps);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    }

    useEffect(() => {
        fetchBattlecardStatus();
    }, []);

    if (loading) return <div className="animate-pulse">Loading battlecards...</div>;

    return (
        <div className="space-y-8 animate-in">
            <div>
                <h1 className="text-3xl font-bold tracking-tight mb-2">Battlecards</h1>
                <p className="text-muted-foreground">Strategic comparison cards generated by AI from latest intelligence.</p>
            </div>

            <div className="grid grid-cols-1 gap-4">
                {competitors.map((comp: any) => (
                    <div key={comp.id} className="bg-card/30 border border-border rounded-2xl overflow-hidden hover:border-primary/30 transition-all group">
                        <div className="p-6 flex flex-col md:flex-row md:items-center justify-between gap-6">
                            <div className="flex items-center gap-4">
                                <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center text-primary">
                                    <ScrollText className="w-6 h-6" />
                                </div>
                                <div>
                                    <h3 className="text-lg font-bold">{comp.name}</h3>
                                    <p className="text-sm text-muted-foreground flex items-center gap-2">
                                        <Clock className="w-3.5 h-3.5" />
                                        Updated: {comp.updated_at ? formatDate(comp.updated_at) : 'Never'}
                                    </p>
                                </div>
                            </div>

                            <div className="flex items-center gap-3">
                                <Link
                                    href={`/battlecards/${comp.id}`}
                                    className="flex items-center gap-2 px-4 py-2 rounded-xl bg-muted/50 hover:bg-muted text-sm font-semibold transition-colors"
                                >
                                    <FileText className="w-4 h-4" />
                                    View Card
                                </Link>
                                <button
                                    onClick={async () => {
                                        if (!confirm(`Generate new AI Battlecard for ${comp.name}?`)) return;
                                        try {
                                            await api.generateBattlecard(comp.id);
                                            alert("Generation started! Refresh in a moment.");
                                            fetchBattlecardStatus();
                                        } catch (err) {
                                            alert("Generation failed. Make sure your LLM API keys are configured.");
                                        }
                                    }}
                                    className="flex items-center gap-2 px-4 py-2 rounded-xl bg-primary/10 text-primary hover:bg-primary/20 text-sm font-semibold transition-colors"
                                >
                                    <Wand2 className="w-4 h-4" />
                                    AI Generate
                                </button>
                            </div>
                        </div>
                    </div>
                ))}

                {competitors.length === 0 && (
                    <div className="py-20 text-center text-muted-foreground border-2 border-dashed border-border rounded-3xl">
                        <AlertCircle className="w-12 h-12 mx-auto mb-4 opacity-20" />
                        <h3 className="text-lg font-semibold">No data available</h3>
                        <p className="text-sm">Add a competitor first to start generating battlecards.</p>
                        <Link href="/competitors" className="mt-6 text-primary font-bold hover:underline inline-block">Go to Competitors</Link>
                    </div>
                )}
            </div>
        </div>
    );
}
